name: CI

on: push

jobs:
  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Lint
        run: |
          pip install flake8
          pip install isort
          make lint

  testing:
    name: Automated Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Cache pip dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --disable-pip-version-check -r requirements.txt
          pip install --disable-pip-version-check -r requirements-extra.txt

      - name: Run unit tests
        run: |
          make test

      - name: Coverage report
        run: |
          make cov-report
